[project]
name = "Exploit_RL"
version = "0.1.0"
description = "Multi-Agent Exploitation Models with Social Learning"
readme = "README.md"
authors = ["Esteban Nocet-Binois <estebann@chalmers.se>"]
license = "MIT"
dependencies = [
    "numba>=0.56.0,<0.57.0",
    "networkx>=2.8.0,<2.9.0",
    "scipy>=1.8.0,<1.9.0",
    "tqdm>=4.64.0,<4.65.0",
    "pandas>=1.4.0,<1.5.0",
    "seaborn>=0.11.0,<0.12.0",
    "matplotlib>=3.5.0,<3.6.0",
    "torch>=1.13.0,<1.14.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.3,<8.4.0",
    "pytest-cov>=6.0.0,<7.0.0",
    "deptry>=0.20.0,<0.21.0",
    "mypy>=1.13.0,<1.14.0",
    "black>=24.10.0,<25.0.0",
    "pylsp-mypy>=0.6.9,<0.7.0",
    "python-lsp-server[all]>=1.12.0,<1.13.0",
]

[build-system]
requires = ["setuptools>=42", "wheel", "hatchling"]
build-backend = "setuptools.build_meta"

[tool.hatch.envs.default]
dependencies = [
    "pytest",
    "pytest-cov",
    "black",
    "mypy",
]

[tool.hatch.envs.default.scripts]
test = "pytest"
lint = "black --check src tests"
typecheck = "mypy src"
